[build]
  command = "bun install && bunx prisma generate && bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"
  SKIP_ENV_VALIDATION = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
